### ISSUE TITLE
Faucet no longer functioning properly (phantom rolls)

### ISSUE THREAD

**Issue by corbinschwartz** [sau412/provably_fair#7]
On https://freegridco.in/#free_roll, the page persistently displays `Wait for xx:xx before next roll`, even if I haven't been to the page in hours. It seems the system believes rolls were made that weren't, the balance doesn't increment, and clicking "view last roll seeds" shows the last roll was made two days ago.

If I leave the page open until the roll button appears and click it, it's replaced by red error text stating `Only one roll in 3600 seconds allowed. Wait xxxx seconds more.`.

**Comment by pachakutiq199999** [comment]
It’s a blank page now
